// <auto-generated />
using System;
using HomeAutomation.ApplicationTier.Entity.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HomeAutomation.ApplicationTier.Entity.Migrations
{
    [DbContext(typeof(HomeAutomationDbContext))]
    [Migration("20230627212152_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("SQL_Latin1_General_CP1_CI_AS")
                .HasAnnotation("ProductVersion", "7.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HomeAutomation.ApplicationTier.Entity.Entities.Building", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Housenumber")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ZipCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id")
                        .HasName("PK__Building__3214EC0751CFC14B");

                    b.ToTable("Building", (string)null);
                });

            modelBuilder.Entity("HomeAutomation.ApplicationTier.Entity.Entities.Device", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Config")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("DeviceType")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id")
                        .HasName("PK__Device__3214EC07D5853B29");

                    b.ToTable("Device", (string)null);
                });

            modelBuilder.Entity("HomeAutomation.ApplicationTier.Entity.Entities.DeviceType", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id")
                        .HasName("PK__DeviceTy__3214EC07A3042A6F");

                    b.ToTable("DeviceType", (string)null);
                });

            modelBuilder.Entity("HomeAutomation.ApplicationTier.Entity.Entities.DeviceValueHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Device")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id")
                        .HasName("PK__DeviceVa__3214EC076F17C0A8");

                    b.ToTable("DeviceValueHistory", (string)null);
                });

            modelBuilder.Entity("HomeAutomation.ApplicationTier.Entity.Entities.Room", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Building")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id")
                        .HasName("PK__Room__3214EC077FD1A548");

                    b.ToTable("Room", (string)null);
                });

            modelBuilder.Entity("HomeAutomation.ApplicationTier.Entity.Entities.Device", b =>
                {
                    b.HasOne("HomeAutomation.ApplicationTier.Entity.Entities.DeviceType", "IdNavigation")
                        .WithOne("Device")
                        .HasForeignKey("HomeAutomation.ApplicationTier.Entity.Entities.Device", "Id")
                        .IsRequired()
                        .HasConstraintName("FK_Device_DeviceType");

                    b.Navigation("IdNavigation");
                });

            modelBuilder.Entity("HomeAutomation.ApplicationTier.Entity.Entities.DeviceValueHistory", b =>
                {
                    b.HasOne("HomeAutomation.ApplicationTier.Entity.Entities.Device", "IdNavigation")
                        .WithOne("DeviceValueHistory")
                        .HasForeignKey("HomeAutomation.ApplicationTier.Entity.Entities.DeviceValueHistory", "Id")
                        .IsRequired()
                        .HasConstraintName("FK_DeviceValueHistory_Device");

                    b.Navigation("IdNavigation");
                });

            modelBuilder.Entity("HomeAutomation.ApplicationTier.Entity.Entities.Room", b =>
                {
                    b.HasOne("HomeAutomation.ApplicationTier.Entity.Entities.Building", "IdNavigation")
                        .WithOne("Room")
                        .HasForeignKey("HomeAutomation.ApplicationTier.Entity.Entities.Room", "Id")
                        .IsRequired()
                        .HasConstraintName("FK_Room_Building");

                    b.Navigation("IdNavigation");
                });

            modelBuilder.Entity("HomeAutomation.ApplicationTier.Entity.Entities.Building", b =>
                {
                    b.Navigation("Room");
                });

            modelBuilder.Entity("HomeAutomation.ApplicationTier.Entity.Entities.Device", b =>
                {
                    b.Navigation("DeviceValueHistory");
                });

            modelBuilder.Entity("HomeAutomation.ApplicationTier.Entity.Entities.DeviceType", b =>
                {
                    b.Navigation("Device");
                });
#pragma warning restore 612, 618
        }
    }
}
